#!/bin/sh

python full_runner.py "0" "0"
python full_runner.py "0" "1"
python full_runner.py "0" "2"
python full_runner.py "0" "3"
python full_runner.py "0" "4"
python full_runner.py "1" "0"
python full_runner.py "1" "1"
python full_runner.py "1" "2"
python full_runner.py "1" "3"
python full_runner.py "1" "4"
python full_runner.py "2" "0"
python full_runner.py "2" "1"
python full_runner.py "2" "2"
python full_runner.py "2" "3"
python full_runner.py "2" "4"
python full_runner.py "5" "0"
python full_runner.py "5" "1"
python full_runner.py "5" "2"
python full_runner.py "5" "3"
python full_runner.py "5" "4"
python full_runner.py "7" "0"
python full_runner.py "7" "1"
python full_runner.py "7" "2"
python full_runner.py "7" "3"
python full_runner.py "7" "4"
