#!/bin/sh

python full_runner.py "3" "0"
python full_runner.py "3" "1"
python full_runner.py "3" "2"
python full_runner.py "3" "3"
python full_runner.py "3" "4"
python full_runner.py "4" "0"
python full_runner.py "4" "1"
python full_runner.py "4" "2"
python full_runner.py "4" "3"
python full_runner.py "4" "4"
python full_runner.py "5" "0"
python full_runner.py "5" "1"
python full_runner.py "5" "2"
python full_runner.py "5" "3"
python full_runner.py "5" "4"
